version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: aws-sdk
    versions:
    - 2.889.0
    - 2.893.0
